/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sipre.vista.configuracion;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author jessica
 */
public class PanelConfiguracion extends javax.swing.JPanel {
    private CardLayout cardLayout;
    /**
     * Creates new form PanelConfiguracion
     */
    public PanelConfiguracion(JFrame frame) {
        cardLayout = new CardLayout();
        JPanel vacio = new JPanel();
        vacio.setBackground(new java.awt.Color(217, 216, 255));
        
        initComponents();
        panelContenido.setLayout(cardLayout);
        panelContenido.add(vacio, "vacio");
        panelContenido.add(new PanelCambioContrasena(), "cambio");
        panelContenido.add(new PanelEliminarCuenta(), "eliminar");
        panelContenido.add(new PanelActualizarDatos(), "actualizar");
        
        cardLayout.show(panelContenido, "vacio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        botonContrasena = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();

        setBackground(new java.awt.Color(217, 216, 255));
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(800, 300));
        setLayout(new java.awt.GridBagLayout());

        botonContrasena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonContrasena.setText("Cambio de contraseña");
        botonContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContrasenaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 49, 0, 0);
        add(botonContrasena, gridBagConstraints);

        botonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonEliminar.setText("Eliminar cuenta");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 49, 0, 0);
        add(botonEliminar, gridBagConstraints);

        botonActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonActualizar.setText("Actualizar datos");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 49, 0, 0);
        add(botonActualizar, gridBagConstraints);

        panelContenido.setBackground(new java.awt.Color(217, 216, 255));
        panelContenido.setMaximumSize(new java.awt.Dimension(300, 224));

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 307;
        gridBagConstraints.ipady = 224;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 40, 37, 37);
        add(panelContenido, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void botonContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContrasenaActionPerformed
        // cambiar contenido a cambio de contraseña
        cardLayout.show(panelContenido, "cambio");
    }//GEN-LAST:event_botonContrasenaActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // cambiar contenido a eliminar cuenta
        cardLayout.show(panelContenido, "eliminar");
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // cambiar contenido a actualizar datos
        cardLayout.show(panelContenido, "actualizar");
    }//GEN-LAST:event_botonActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonContrasena;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JPanel panelContenido;
    // End of variables declaration//GEN-END:variables
}
