/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sipre.vista.consultar;

import com.mycompany.sipre.modelo.Documento;
import com.mycompany.sipre.controlador.DocumentoController;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jessica
 */
public class PanelDisp extends javax.swing.JPanel {

    /**
     * Creates new form PanelDisp
     */
    public PanelDisp(JFrame frame) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ComboFiltro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(217, 216, 255));
        setPreferredSize(new java.awt.Dimension(587, 300));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Disponibilidad de documentos en bodega");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 211, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Seleccione el Estatus de los documento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 181, 0, 0);
        add(jLabel2, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(148, 143, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 237, 0, 0);
        add(jButton1, gridBagConstraints);

        ComboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En bodega", "Solicitado", "Todos"}));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 85, 0, 6);
        add(ComboFiltro, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Formato", "Folio", "Cantidad disponible", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(148, 143, 255));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 601;
        gridBagConstraints.ipady = 201;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 32, 6);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String estatusSeleccionado = ComboFiltro.getSelectedItem().toString();

        DocumentoController documentoDAO = new DocumentoController();
        List<Documento> documentos = null;

        if ("Todos".equals(estatusSeleccionado)) {
            // Si el estatus es "Todos", buscar los documentos con ambos estatus
            AtomicReference<List<Documento>> refEnBodega = new AtomicReference<>();
            AtomicReference<List<Documento>> refSolicitados = new AtomicReference<>();

            documentoDAO.obtenerDocumentosPorEstatus("En bodega", respuesta -> {
                refEnBodega.set(respuesta);

                documentoDAO.obtenerDocumentosPorEstatus("Solicitado", respuesta2 -> {
                    refSolicitados.set(respuesta2);

                    List<Documento> documentosCombinados = new ArrayList<>();
                    if (refEnBodega.get() != null) {
                        documentosCombinados.addAll(refEnBodega.get());
                    }
                    if (refSolicitados.get() != null) {
                        documentosCombinados.addAll(refSolicitados.get());
                    }
                    actualizarTabla(documentosCombinados);
                });
            });
        } else {
            // Si no es "Todos", buscar solo el estatus seleccionado
            documentoDAO.obtenerDocumentosPorEstatus(estatusSeleccionado, respuesta -> {
                actualizarTabla(respuesta);

            });
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    private void actualizarTabla(List<Documento> documentos) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Limpiar tabla

        if (documentos != null) {
            for (Documento documento : documentos) {
                model.addRow(new Object[]{
                    documento.getTipoDocumento(),
                    documento.getFolio(),
                    documento.getCantidadDocumentos(),
                    documento.getEstatus()
                });
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al cargar documentos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
