/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sipre.vista.reportes;

//import com.mycompany.sipre.controlador.GenerarReportes;
import com.opencsv.CSVWriter;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.FileWriter;

/**
 *
 * @author DELL
 */
public class PanelMovimientos_solicitudes extends javax.swing.JPanel {

    /**
     * Creates new form PanelMovimientos_solicitudes
     */

    public PanelMovimientos_solicitudes(JFrame frame) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private DefaultTableModel tableModel;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("Generar reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });


        String[] columnNames = {"id_movimiento", "tipo_movimiento", "tipo_documento", "cantidad", "fecha", "nombre_usuario"};
        tableModel = new DefaultTableModel(columnNames, 0);
        jTable1.setModel(tableModel);
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(148, 143, 255));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Generar csv");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(296, 296, 296)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(306, 306, 306)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tableModel.setRowCount(0);
        //GenerarReportes.cargarDatosMovimientos(tableModel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        exportarCsv(tableModel,"reporte_movimientos.csv");
    }//GEN-LAST:event_jButton2ActionPerformed
    public  void exportarCsv(DefaultTableModel tableModel, String fileName) {
        try (CSVWriter writer = new CSVWriter(new FileWriter(fileName))) {
            // Escribir encabezados
            String[] headers = {"ID Movimiento", "Tipo Movimiento", "Tipo Documento", "Cantidad", "Fecha", "Usuario"};
            writer.writeNext(headers);

            // Escribir datos
            for (int i = 0; i < tableModel.getRowCount(); i++) {
                String idMovimiento = tableModel.getValueAt(i, 0).toString();
                String tipoMovimiento = tableModel.getValueAt(i, 1).toString();
                String tipoDocumento = tableModel.getValueAt(i, 2).toString();
                String cantidad = tableModel.getValueAt(i, 3).toString();
                String fecha = tableModel.getValueAt(i, 4).toString();
                String usuario = tableModel.getValueAt(i, 5).toString();

                // Crear una fila con los datos
                String[] row = {idMovimiento, tipoMovimiento, tipoDocumento, cantidad, fecha, usuario};
                writer.writeNext(row);
            }

            JOptionPane.showMessageDialog(this, "Datos exportados a: " + fileName, "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al exportar los datos a CSV.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
