/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sipre.vista;

import com.mycompany.sipre.modelo.Usuario;
import com.mycompany.sipre.vista.configuracion.PanelConfiguracion;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import com.mycompany.sipre.controlador.UsuarioController;
import com.mycompany.sipre.modelo.Usuario;
import com.mycompany.sipre.vista.alta.PanelAlta;
import com.mycompany.sipre.vista.alta.PanelConsulta;
import com.mycompany.sipre.vista.consultar.*;
import com.mycompany.sipre.vista.gestion.PanelAgregarTiposFP;
import com.mycompany.sipre.vista.gestion.PanelEditarTiposFP;
import com.mycompany.sipre.vista.gestion.PanelGestionRol;
import com.mycompany.sipre.vista.gestion.PanelUsuarios;
import com.mycompany.sipre.vista.reportes.PanelReporteExcelYPDF;
import com.mycompany.sipre.vista.solicitar.*;
import com.mycompany.sipre.vista.reportes.Panelinventario;
//import com.mycompany.sipre.vista.solicitar.reportes.PanelMovimientos_solicitudes;
import com.mycompany.sipre.vista.reportes.PanelReporteExcelYPDF;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author jessica
 */
public class AdminJFrame extends JFrame {
    private CardLayout cardLayout;
    private JPanel panelContenedor;
    private Usuario usuario;
    /**
     * Creates new form Main
     */
    public AdminJFrame(Usuario usuario) {
        // configuración general del jframe
        setTitle("Sistema SIPRE");
        setSize(1080,720);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setMinimumSize(new Dimension(800,600));
        this.usuario = usuario;
        
        // panel que contiene los 2 jmenubars
        JPanel panelMenu = new JPanel();
        panelMenu.setLayout(new BoxLayout(panelMenu, BoxLayout.Y_AXIS));
        
        // panel para el contenido principal
        cardLayout = new CardLayout();
        panelContenedor = new JPanel(cardLayout);
        
        // agregar todos los paneles al panelContenedor para poder mostrarlos dinamicamente
        panelContenedor.add("inicio", new PanelInicio(this));
        panelContenedor.add("info", new PanelInfo(this, usuario));
        panelContenedor.add("config", new PanelConfiguracion(this));
        panelContenedor.add("gestion", new PanelGestion(this));
        panelContenedor.add("ayuda", new PanelAyuda(this));
        panelContenedor.add("usuarios", new PanelUsuarios());
        panelContenedor.add("roles", new PanelGestionRol());
        panelContenedor.add("tipos", new PanelAgregarTiposFP());
        panelContenedor.add("editar", new PanelEditarTiposFP());
        panelContenedor.add("alta", new PanelAlta(usuario.getId()));
        panelContenedor.add("consulta", new PanelConsulta());
        panelContenedor.add("gestion", new PanelGestion(this));
        panelContenedor.add("reporteExcelYPDF", new PanelReporteExcelYPDF());
        
        initComponents();
        
        // agregar los 2 jmenubars al panel de menú
        panelMenu.add(jMenuBar1);
        panelMenu.add(jMenuBar2);
        
        // agregar el panel de menú y panel de contenido al jframe
        setLayout(new BorderLayout());
        add(panelMenu, BorderLayout.NORTH);
        add(panelContenedor, BorderLayout.CENTER);
        pack();
    }
    
    // Método para cambiar contenido y título del jframe
    public void mostrarPanel(String nombrePanel, String titulo) {
        cardLayout.show(panelContenedor, nombrePanel);
        setTitle(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        menuGestion = new javax.swing.JMenu();
        menuGestionFormatos = new javax.swing.JMenuItem();
        menuFormatos = new javax.swing.JMenuItem();
        menuModificar = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenuItem();
        menuRoles = new javax.swing.JMenuItem();
        menuSolicitar = new javax.swing.JMenu();
        menuAlta = new javax.swing.JMenuItem();
        menuConsultar = new javax.swing.JMenuItem();
        menuGenerar = new javax.swing.JMenu();
        menuEstadistico = new javax.swing.JMenuItem();
        menuExistencias = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        textoModalidad = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCuenta = new javax.swing.JMenu();
        menuInfo = new javax.swing.JMenuItem();
        menuConfiguracion = new javax.swing.JMenuItem();
        cerrarSesion = new javax.swing.JMenuItem();
        menuModalidad = new javax.swing.JMenu();
        modalidadUsuario = new javax.swing.JMenuItem();
        modalidadAdmin = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuBar2.setBackground(new java.awt.Color(77, 77, 77));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jMenuBar2.setMaximumSize(new java.awt.Dimension(1280, 23));
        jMenuBar2.setMinimumSize(new java.awt.Dimension(800, 23));
        jMenuBar2.setPreferredSize(new java.awt.Dimension(800, 23));

        menuGestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        menuGestion.setText("Gestión");
        menuGestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuGestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuGestion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuGestion.setMargin(new java.awt.Insets(3, 20, 3, 20));
        menuGestion.setMaximumSize(new java.awt.Dimension(100, 50));
        menuGestion.setMinimumSize(new java.awt.Dimension(100, 50));
        menuGestion.setOpaque(true);
        menuGestion.setPreferredSize(new java.awt.Dimension(100, 50));

        menuGestionFormatos.setText("Gestión de formatos preimpresos");
        menuGestionFormatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionFormatosActionPerformed(evt);
            }
        });
        menuGestion.add(menuGestionFormatos);

        menuFormatos.setText("Añadir nuevos tipos de formatos preimpresos");
        menuFormatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormatosActionPerformed(evt);
            }
        });
        menuGestion.add(menuFormatos);

        menuModificar.setText("Modificar formatos preimpresos");
        menuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModificarActionPerformed(evt);
            }
        });
        menuGestion.add(menuModificar);

        menuUsuarios.setText("Crear, modificar o eliminar usuarios");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        menuGestion.add(menuUsuarios);

        menuRoles.setText("Asignar y modificar permisos de acceso");
        menuRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRolesActionPerformed(evt);
            }
        });
        menuGestion.add(menuRoles);

        jMenuBar2.add(menuGestion);

        menuSolicitar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        menuSolicitar.setText("Alta de formatos");
        menuSolicitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSolicitar.setMaximumSize(new java.awt.Dimension(100, 50));
        menuSolicitar.setMinimumSize(new java.awt.Dimension(100, 50));
        menuSolicitar.setOpaque(true);
        menuSolicitar.setPreferredSize(new java.awt.Dimension(100, 50));

        menuAlta.setText("Alta de formatos");
        menuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAltaActionPerformed(evt);
            }
        });
        menuSolicitar.add(menuAlta);

        menuConsultar.setText("Consultar estado de formatos preimpresos");
        menuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarActionPerformed(evt);
            }
        });
        menuSolicitar.add(menuConsultar);

        jMenuBar2.add(menuSolicitar);

        menuGenerar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        menuGenerar.setText("Generar");
        menuGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuGenerar.setMaximumSize(new java.awt.Dimension(100, 50));
        menuGenerar.setMinimumSize(new java.awt.Dimension(100, 50));
        menuGenerar.setOpaque(true);
        menuGenerar.setPreferredSize(new java.awt.Dimension(100, 50));

        menuEstadistico.setText("Reportes estadísticos");
        menuEstadistico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstadisticoActionPerformed(evt);
            }
        });
        menuGenerar.add(menuEstadistico);

        jMenuBar2.add(menuGenerar);

        menuAyuda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        menuAyuda.setText("Ayuda");
        menuAyuda.setActionCommand("ayuda");
        menuAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAyuda.setMaximumSize(new java.awt.Dimension(100, 50));
        menuAyuda.setMinimumSize(new java.awt.Dimension(100, 50));
        menuAyuda.setOpaque(true);
        menuAyuda.setPreferredSize(new java.awt.Dimension(100, 50));
        menuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAyudaActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ayuda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAyuda.add(jMenuItem1);

        jMenuBar2.add(menuAyuda);

        textoModalidad.setBackground(new java.awt.Color(77, 77, 77));
        textoModalidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        textoModalidad.setForeground(new java.awt.Color(255, 255, 255));
        textoModalidad.setText("Modalidad: Administrador");
        textoModalidad.setFocusable(false);
        textoModalidad.setMaximumSize(new java.awt.Dimension(400, 50));
        textoModalidad.setMinimumSize(new java.awt.Dimension(100, 50));
        textoModalidad.setPreferredSize(new java.awt.Dimension(100, 50));
        textoModalidad.setRequestFocusEnabled(false);
        jMenuBar2.add(textoModalidad);

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(1280, 23));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(800, 23));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(800, 23));

        menuCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        menuCuenta.setForeground(new java.awt.Color(255, 255, 255));
        menuCuenta.setText(usuario.getNombre());
        menuCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCuenta.setMaximumSize(new java.awt.Dimension(500, 50));
        menuCuenta.setMinimumSize(new java.awt.Dimension(200, 50));
        menuCuenta.setPreferredSize(new java.awt.Dimension(400, 50));

        menuInfo.setText("Información personal");
        menuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoActionPerformed(evt);
            }
        });
        menuCuenta.add(menuInfo);

        menuConfiguracion.setText("Configuración");
        menuConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfiguracionActionPerformed(evt);
            }
        });
        menuCuenta.add(menuConfiguracion);

        cerrarSesion.setText("Cerrar sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        menuCuenta.add(cerrarSesion);

        jMenuBar1.add(Box.createHorizontalStrut(200));

        jMenuBar1.add(menuCuenta);

        menuModalidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        menuModalidad.setForeground(new java.awt.Color(255, 255, 255));
        menuModalidad.setText("Modalidad");
        menuModalidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuModalidad.setMaximumSize(new java.awt.Dimension(100, 50));
        menuModalidad.setPreferredSize(new java.awt.Dimension(100, 50));

        modalidadUsuario.setText("Usuario");
        modalidadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modalidadUsuarioActionPerformed(evt);
            }
        });
        menuModalidad.add(modalidadUsuario);

        modalidadAdmin.setText("Administrador");
        modalidadAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modalidadAdminActionPerformed(evt);
            }
        });
        menuModalidad.add(modalidadAdmin);

        jMenuBar1.add(menuModalidad);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoActionPerformed
        // cambiar contenido a panel de información personal
        mostrarPanel("info", "Información personal");
    }//GEN-LAST:event_menuInfoActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        // mostrar dialogo para confirmar cerrar sesión
        Object[] options = {"Cancelar", "Cerrar sesión"};
        int opcion = JOptionPane.showOptionDialog(panelContenedor, "¿Desea cerrar sesión?", "Cerrar sesión", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if (opcion == 1) { 
            //cerrar mainjframe y mostrar dialogo de login
            this.dispose();
            DialogoLogin dialogoLogin = new DialogoLogin(null, new UsuarioController());
            dialogoLogin.setVisible(true);
            
            if (dialogoLogin.isAutenticado()) { //crear nuevo mainjframe al iniciar sesion
                switch (dialogoLogin.getRol()) {
                    case "administrador":
                        AdminJFrame frameAdmin = new AdminJFrame(dialogoLogin.getUsuarioAutenticado());
                        frameAdmin.setVisible(true);
                        break;
                    case "registrador":
                        MainJFrame frameRegistrador = new MainJFrame(dialogoLogin.getUsuarioAutenticado());
                        frameRegistrador.setVisible(true);
                        break;
                    case "consultador":
                        ConsultorJFrame frameConsultador = new ConsultorJFrame(dialogoLogin.getUsuarioAutenticado());
                        frameConsultador.setVisible(true);
                        break;
                }
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void menuConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfiguracionActionPerformed
        // cambiar contenido a panel de configuracion
        mostrarPanel("config", "Configuración");
    }//GEN-LAST:event_menuConfiguracionActionPerformed

    private void modalidadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modalidadUsuarioActionPerformed
        // TODO: agregar funcionalidad para cambiar a modalidad de usuario
    }//GEN-LAST:event_modalidadUsuarioActionPerformed

    private void modalidadAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modalidadAdminActionPerformed
        // TODO: agregar funcionalidad para cambiar a modalidad de administrador
    }//GEN-LAST:event_modalidadAdminActionPerformed

    private void menuFormatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormatosActionPerformed
        // cambiar contenido a panel de buscar por folio
        mostrarPanel("tipos", "Agregar tipos de formatos preimpresos");
    }//GEN-LAST:event_menuFormatosActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        // cambiar contenido a panel de buscar por tipo
        mostrarPanel("usuarios", "Gestionar usuarios");
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuEstadisticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstadisticoActionPerformed
        // cambiar contenido a panel de consultar certificados
        mostrarPanel("reporteExcelYPDF", "Consultar certificados");
    }//GEN-LAST:event_menuEstadisticoActionPerformed

    private void menuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAltaActionPerformed
        // cambiar contenido a panel alta formatos
        mostrarPanel("alta", "Alta de formatos");
    }//GEN-LAST:event_menuAltaActionPerformed

    private void menuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAyudaActionPerformed
         
    }//GEN-LAST:event_menuAyudaActionPerformed
    //menuMovimientosActionPerformed
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        mostrarPanel("ayuda", "Ayuda");
        
    }                                          
    //menuInventarioActionPerformed
    private void menuInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        mostrarPanel("inventario", "Reporte Inventario");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRolesActionPerformed
        mostrarPanel("roles", "Gestionar roles");
    }//GEN-LAST:event_menuRolesActionPerformed

    private void menuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModificarActionPerformed
        // TODO add your handling code here:
        mostrarPanel("editar", "Editar tipos de formatos preimpresos");
    }//GEN-LAST:event_menuModificarActionPerformed

    private void menuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarActionPerformed
        // TODO add your handling code here:
        mostrarPanel("consulta", "Consultar formatos");
    }//GEN-LAST:event_menuConsultarActionPerformed

    private void menuGestionFormatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionFormatosActionPerformed
        // TODO add your handling code here:
        mostrarPanel("gestion", "Gestionar formatos preimpresos");
    }//GEN-LAST:event_menuGestionFormatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cerrarSesion;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menuAlta;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuItem menuConfiguracion;
    private javax.swing.JMenuItem menuConsultar;
    private javax.swing.JMenu menuCuenta;
    private javax.swing.JMenuItem menuEstadistico;
    private javax.swing.JMenuItem menuExistencias;
    private javax.swing.JMenuItem menuFormatos;
    private javax.swing.JMenu menuGenerar;
    private javax.swing.JMenu menuGestion;
    private javax.swing.JMenuItem menuGestionFormatos;
    private javax.swing.JMenuItem menuInfo;
    private javax.swing.JMenu menuModalidad;
    private javax.swing.JMenuItem menuModificar;
    private javax.swing.JMenuItem menuRoles;
    private javax.swing.JMenu menuSolicitar;
    private javax.swing.JMenuItem menuUsuarios;
    private javax.swing.JMenuItem modalidadAdmin;
    private javax.swing.JMenuItem modalidadUsuario;
    private javax.swing.JMenu textoModalidad;
    // End of variables declaration//GEN-END:variables
}
