/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sipre.vista;

import com.mycompany.sipre.modelo.Usuario;
import javax.swing.JFrame;

/**
 *
 * @author jessica
 */
public class PanelInfo extends javax.swing.JPanel {
    private Usuario usuario;
    /**
     * Creates new form PanelInfo
     */
    public PanelInfo(JFrame frame, Usuario usuario) {
        this.usuario = usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LabelNombre = new javax.swing.JLabel();
        LabelDomicilio = new javax.swing.JLabel();
        LabelFecha = new javax.swing.JLabel();
        LabelSexo = new javax.swing.JLabel();
        LabelCorreo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(217, 216, 255));
        setPreferredSize(new java.awt.Dimension(587, 300));
        setLayout(new java.awt.GridBagLayout());

        LabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelNombre.setText("Nombre: " + usuario.getNombreCompleto());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 49, 0, 0);
        add(LabelNombre, gridBagConstraints);

        LabelDomicilio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDomicilio.setText("Domicilio: " + usuario.getDomicilio());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 0, 0);
        add(LabelDomicilio, gridBagConstraints);

        LabelFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelFecha.setText("Fecha de nacimiento: " + usuario.getFechaNacimiento());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 0, 0);
        add(LabelFecha, gridBagConstraints);

        LabelSexo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelSexo.setText("Sexo: " + usuario.getSexo());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 49, 123, 0);
        add(LabelSexo, gridBagConstraints);

        LabelCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelCorreo.setText("Correo electrónico: " + usuario.getCorreo());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 138, 0, 176);
        add(LabelCorreo, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCorreo;
    private javax.swing.JLabel LabelDomicilio;
    private javax.swing.JLabel LabelFecha;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelSexo;
    // End of variables declaration//GEN-END:variables
}
